---
title: "Challenge 7: Out of an abundance of caution . . . "
output:
  md_document:
  variant: markdown_github
---

# Challenge 7: Out of an abundance of caution . . .
- *Assigned: February 8, 2019*
- *Due: at 6pm on February 15, 2019*

# Assignment
You should have received an email invitation to access this assigment in Github Classroom.  If you haven't received it, please [post an Issue](https://github.com/IBIEM/community/issues)

The goal of this challenge is for you to begin working with phyloseq, and use phyloseq to start making some standard plots: Relative abundance plots and alpha diversity plots.

You will need to:

1. Initialize a new project in RStudio based on this repository (you might want to review the [relevant instructions from Challenge 1](https://github.com/IBIEM/challenge_1/blob/master/README.Rmd#initialize-a-new-project))

2. Fill the blank R code chunks in [challenge7_assignment.Rmd](challenge7_assignment.Rmd)

3. Modify the header of [challenge7_assignment.Rmd](challenge7_assignment.Rmd) (you might want to review the [relevant instructions from Challenge 1](https://github.com/IBIEM/challenge_1/blob/master/README.Rmd#modify-the-header)

4. Submit the Assignment (you might want to review the [relevant instructions from Challenge 1](https://github.com/IBIEM/challenge_1/blob/master/README.Rmd#submitting-the-assignment) ).  You should submit the following:
    - `challenge7_assignment.Rmd` : your modified version of the R Notebook that you received in your repo
    - `challenge7_assignment.html` : the output from knitting your revised `challenge6_assignment.Rmd`


5. Optional (but *strongly* recommended): frequently commit changes and push to GitHub.

We strongly recommend that you start working on this immediately so you will have time to get any help that you need.  If you have questions about this assignment outside of class, please [post an Issue](https://github.com/IBIEM/community/issues) to the discussion forum.

## Grading
For this assignment and future assignments we will be checking for:

| Weight (%) | Component                  |
|------------|----------------------------|
|         70 | Correct Result             |
|         15 | Code Quality               |
|         10 | Git Commit Message Quality |
|          5 | SessionInfo                |


### Git Commit Message Quality
  - For some helpful hints [search the internet for "writing good commit messages"](https://duckduckgo.com/?q=writing+good+commit+messages)
  - You may also want [examples of what not to do](https://xkcd.com/1296/)

### SessionInfo
Including a `SessionInfo` statement at the end of your R Notebook is good reproducibility practice.

